//HintName: MeterReadingEntry.g.cs
// <auto-generated/>
namespace Test
{
    public partial class MeterReadingEntry 
    {
        public static MeterReadingEntry FromBigQueryRow(Google.Cloud.BigQuery.V2.BigQueryRow row)
        {
            return new MeterReadingEntry
            {
                PropertyId = row["PropertyId"] is string ___PropertyId ? ___PropertyId : default,
                RentRollId = row["RentRollId"] is string ___RentRollId ? ___RentRollId : default,
                SerialNumber = row["SerialNumber"] is string ___SerialNumber ? ___SerialNumber : default,
                Gallons = row["Gallons"] is double ___Gallons ? ___Gallons : default,
                Events = row["Events"] is double ___Events ? ___Events : default,
                FlowTime = row["FlowTime"] is double ___FlowTime ? ___FlowTime : default,
                Hour = row["Hour"] is DateTime ___Hour ? ___Hour : default,
                RunningHours = row["RunningHours"] is long ___RunningHours ? ___RunningHours : default,
                CatchupFlag = row["CatchupFlag"] is string ___CatchupFlag ? ___CatchupFlag : default,
                LeakStatus = row["LeakStatus"] is string ___LeakStatus ? ___LeakStatus : default,
                LeakDetails = row["LeakDetails"] is string ___LeakDetails ? ___LeakDetails : default,
                ToiletLeak = row["ToiletLeak"] is double ___ToiletLeak ? ___ToiletLeak : default,
                MiscellaneousLeak = row["MiscellaneousLeak"] is double ___MiscellaneousLeak ? ___MiscellaneousLeak : default,
                DailyGallonsLeaked = row["DailyGallonsLeaked"] is double ___DailyGallonsLeaked ? ___DailyGallonsLeaked : default,
                DailyLeakStatus = row["DailyLeakStatus"] is string ___DailyLeakStatus ? ___DailyLeakStatus : default,
                LeakGallons22Hours = row["LeakGallons22Hours"] is double ___LeakGallons22Hours ? ___LeakGallons22Hours : default,
                DateLeakStarted = row["DateLeakStarted"] is DateTime ___DateLeakStarted ? ___DateLeakStarted : default,
                GallonsSinceLastLeak = row["GallonsSinceLastLeak"] is double ___GallonsSinceLastLeak ? ___GallonsSinceLastLeak : default,
                LastLeakingAt = row["LastLeakingAt"] is DateTime ___LastLeakingAt ? ___LastLeakingAt : default,
                DeveloperName = row["DeveloperName"] is string ___DeveloperName ? ___DeveloperName : default,
                GpdFilter = row["GpdFilter"] is string ___GpdFilter ? ___GpdFilter : default,
                FlowTimeFormatted = row["FlowTimeFormatted"] is string ___FlowTimeFormatted ? ___FlowTimeFormatted : default,
                RanMoreThan22Hours = row["RanMoreThan22Hours"] is string ___RanMoreThan22Hours ? ___RanMoreThan22Hours : default,
                HourlyReadingStatus = row["HourlyReadingStatus"] is long ___HourlyReadingStatus ? ___HourlyReadingStatus : default,
                DaysRepeating = row["DaysRepeating"] is long ___DaysRepeating ? ___DaysRepeating : default,
                UnitDetails = row["UnitDetails"] is string ___UnitDetails ? ___UnitDetails : default,
                HoursRunningMoreThan55Minutes = row["HoursRunningMoreThan55Minutes"] is long ___HoursRunningMoreThan55Minutes ? ___HoursRunningMoreThan55Minutes : default,
                LeakGallons = row["LeakGallons"] is double ___LeakGallons ? ___LeakGallons : default,
                WarningLeakGallons = row["WarningLeakGallons"] is double ___WarningLeakGallons ? ___WarningLeakGallons : default,
                UrgentLeakGallons = row["UrgentLeakGallons"] is double ___UrgentLeakGallons ? ___UrgentLeakGallons : default,
                LatestLeakStatus = row["LatestLeakStatus"] is string ___LatestLeakStatus ? ___LatestLeakStatus : default,
                TimeSinceLastReading = row["TimeSinceLastReading"] is string ___TimeSinceLastReading ? ___TimeSinceLastReading : default,
                DpoeHourlyEvents = row["DpoeHourlyEvents"] is string ___DpoeHourlyEvents ? ___DpoeHourlyEvents : default,
                DpoeHourlyGallons = row["DpoeHourlyGallons"] is string ___DpoeHourlyGallons ? ___DpoeHourlyGallons : default,
                DpoeHourlyFlowTime = row["DpoeHourlyFlowTime"] is string ___DpoeHourlyFlowTime ? ___DpoeHourlyFlowTime : default,
            };
        }
    }
}