//HintName: BigQueryMappedAttribute.g.cs
// <auto-generated/>
namespace BigQueryMapping{
    [System.AttributeUsage(SystemAttributeTargets.Class)]
    public class BigQueryMappedAttribute : System.Attribute
    {
    }
}