//HintName: BigQueryMappedAttribute.g.cs
// <auto-generated/>
namespace BigQueryMapping {
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class BigQueryMappedAttribute : System.Attribute
    {
    }
}