//HintName: MeterReadingEntry.g.cs
// <auto-generated/>
namespace Fake.Namespace
{
    public partial class MeterReadingEntry : BigQueryMapping.IBigQueryGenerated<MeterReadingEntry>
    {
        public static MeterReadingEntry FromBigQueryRow(Google.Cloud.BigQuery.V2.BigQueryRow row)
        {
            return new MeterReadingEntry
            {
                PropertyId = row["PropertyID"] is string ___PropertyId ? ___PropertyId : null,
                RentRollId = row["Property_RentRoll_ID"] is string ___RentRollId ? ___RentRollId : null,
                SerialNumber = row["header_serial_number"] is string ___SerialNumber ? ___SerialNumber : null,
                Gallons = row["Gallons"] is double ___Gallons ? ___Gallons : null,
                Events = row["Events"] is double ___Events ? ___Events : null,
                FlowTime = row["Flowtime"] is double ___FlowTime ? ___FlowTime : null,
                Hour = row["hour"] is System.DateTime ___Hour ? ___Hour : null,
                RunningHours = row["Running_hours"] is long ___RunningHours ? ___RunningHours : null,
                CatchupFlag = row["CatchupFlag"] is string ___CatchupFlag ? ___CatchupFlag : null,
                LeakStatus = row["Leak_Status"] is string ___LeakStatus ? ___LeakStatus : null,
                LeakDetails = row["Leak_Details"] is string ___LeakDetails ? ___LeakDetails : null,
                ToiletLeak = row["toilet_leak"] is double ___ToiletLeak ? ___ToiletLeak : null,
                MiscellaneousLeak = row["Miscellaneous_Leaks"] is double ___MiscellaneousLeak ? ___MiscellaneousLeak : null,
                DailyGallonsLeaked = row["daily_leak_gallon_total"] is double ___DailyGallonsLeaked ? ___DailyGallonsLeaked : null,
                DailyLeakStatus = row["daily_leak_status"] is string ___DailyLeakStatus ? ___DailyLeakStatus : null,
                LeakGallons22Hours = row["Leak_Gallons_22_hours"] is double ___LeakGallons22Hours ? ___LeakGallons22Hours : null,
                DateLeakStarted = row["DateLeakStarted"] is System.DateTime ___DateLeakStarted ? ___DateLeakStarted : null,
                GallonsSinceLastLeak = row["Total_gallons_since_leak"] is double ___GallonsSinceLastLeak ? ___GallonsSinceLastLeak : null,
                LastLeakingAt = row["last_leaking_at"] is System.DateTime ___LastLeakingAt ? ___LastLeakingAt : null,
                DeveloperName = row["Developer"] is string ___DeveloperName ? ___DeveloperName : null,
                GpdFilter = row["GPD_Filter"] is string ___GpdFilter ? ___GpdFilter : null,
                FlowTimeFormatted = row["FlowtimeHHmm"] is string ___FlowTimeFormatted ? ___FlowTimeFormatted : null,
                RanMoreThan22Hours = row["ran_more_than_22h"] is string ___RanMoreThan22Hours ? ___RanMoreThan22Hours : null,
                HourlyReadingStatus = row["hourly_reading_status_num"] is long ___HourlyReadingStatus ? ___HourlyReadingStatus : null,
                DaysRepeating = row["Days_Repeating"] is long ___DaysRepeating ? ___DaysRepeating : null,
                UnitDetails = row["Unit_Details"] is string ___UnitDetails ? ___UnitDetails : null,
                HoursRunningMoreThan55Minutes = row["Hours_running_55min_Daily"] is long ___HoursRunningMoreThan55Minutes ? ___HoursRunningMoreThan55Minutes : null,
                LeakGallons = row["Leak_Gallons"] is double ___LeakGallons ? ___LeakGallons : null,
                WarningLeakGallons = row["Orange_Leak_Gallons"] is double ___WarningLeakGallons ? ___WarningLeakGallons : null,
                UrgentLeakGallons = row["Red_Leak_Gallons"] is double ___UrgentLeakGallons ? ___UrgentLeakGallons : null,
                NonNullableProperty = row["Something"] is double ___NonNullableProperty ? ___NonNullableProperty : default,
                LatestLeakStatus = row["Latest_Leak_Status"] is string ___LatestLeakStatus ? ___LatestLeakStatus : null,
                TimeSinceLastReading = row["duration_since_last_reading"] is string ___TimeSinceLastReading ? ___TimeSinceLastReading : null,
                DpoeHourlyEvents = row["DPOE_hourly_events_hot_cold"] is string ___DpoeHourlyEvents ? ___DpoeHourlyEvents : null,
                DpoeHourlyGallons = row["DPOE_hourly_gallons_hot_cold"] is string ___DpoeHourlyGallons ? ___DpoeHourlyGallons : null,
                DpoeHourlyFlowTime = row["DPOE_hourly_flowtime_hot_cold"] is string ___DpoeHourlyFlowTime ? ___DpoeHourlyFlowTime : null,
            };
        }
    }
}