//HintName: MeterReadingEntry.g.cs
// <auto-generated/>
namespace Fake.Namespace
{
    public partial class MeterReadingEntry : BigQueryMapping.IBigQueryGenerated<MeterReadingEntry>
    {
        public static MeterReadingEntry FromBigQueryRow(Google.Cloud.BigQuery.V2.BigQueryRow row)
        {
            return new MeterReadingEntry
            {
                PropertyId = row["PropertyID"] is string ___PropertyId ? ___PropertyId : default,
                RentRollId = row["Property_RentRoll_ID"] is string ___RentRollId ? ___RentRollId : default,
                SerialNumber = row["header_serial_number"] is string ___SerialNumber ? ___SerialNumber : default,
                Gallons = row["Gallons"] is double ___Gallons ? ___Gallons : default,
                Events = row["Events"] is double ___Events ? ___Events : default,
                FlowTime = row["Flowtime"] is double ___FlowTime ? ___FlowTime : default,
                Hour = row["hour"] is DateTime ___Hour ? ___Hour : default,
                RunningHours = row["Running_hours"] is long ___RunningHours ? ___RunningHours : default,
                CatchupFlag = row["CatchupFlag"] is string ___CatchupFlag ? ___CatchupFlag : default,
                LeakStatus = row["Leak_Status"] is string ___LeakStatus ? ___LeakStatus : default,
                LeakDetails = row["Leak_Details"] is string ___LeakDetails ? ___LeakDetails : default,
                ToiletLeak = row["toilet_leak"] is double ___ToiletLeak ? ___ToiletLeak : default,
                MiscellaneousLeak = row["Miscellaneous_Leaks"] is double ___MiscellaneousLeak ? ___MiscellaneousLeak : default,
                DailyGallonsLeaked = row["daily_leak_gallon_total"] is double ___DailyGallonsLeaked ? ___DailyGallonsLeaked : default,
                DailyLeakStatus = row["daily_leak_status"] is string ___DailyLeakStatus ? ___DailyLeakStatus : default,
                LeakGallons22Hours = row["Leak_Gallons_22_hours"] is double ___LeakGallons22Hours ? ___LeakGallons22Hours : default,
                DateLeakStarted = row["DateLeakStarted"] is DateTime ___DateLeakStarted ? ___DateLeakStarted : default,
                GallonsSinceLastLeak = row["Total_gallons_since_leak"] is double ___GallonsSinceLastLeak ? ___GallonsSinceLastLeak : default,
                LastLeakingAt = row["last_leaking_at"] is DateTime ___LastLeakingAt ? ___LastLeakingAt : default,
                DeveloperName = row["Developer"] is string ___DeveloperName ? ___DeveloperName : default,
                GpdFilter = row["GPD_Filter"] is string ___GpdFilter ? ___GpdFilter : default,
                FlowTimeFormatted = row["FlowtimeHHmm"] is string ___FlowTimeFormatted ? ___FlowTimeFormatted : default,
                RanMoreThan22Hours = row["ran_more_than_22h"] is string ___RanMoreThan22Hours ? ___RanMoreThan22Hours : default,
                HourlyReadingStatus = row["hourly_reading_status_num"] is long ___HourlyReadingStatus ? ___HourlyReadingStatus : default,
                DaysRepeating = row["Days_Repeating"] is long ___DaysRepeating ? ___DaysRepeating : default,
                UnitDetails = row["Unit_Details"] is string ___UnitDetails ? ___UnitDetails : default,
                HoursRunningMoreThan55Minutes = row["Hours_running_55min_Daily"] is long ___HoursRunningMoreThan55Minutes ? ___HoursRunningMoreThan55Minutes : default,
                LeakGallons = row["Leak_Gallons"] is double ___LeakGallons ? ___LeakGallons : default,
                WarningLeakGallons = row["Orange_Leak_Gallons"] is double ___WarningLeakGallons ? ___WarningLeakGallons : default,
                UrgentLeakGallons = row["Red_Leak_Gallons"] is double ___UrgentLeakGallons ? ___UrgentLeakGallons : default,
                LatestLeakStatus = row["Latest_Leak_Status"] is string ___LatestLeakStatus ? ___LatestLeakStatus : default,
                TimeSinceLastReading = row["duration_since_last_reading"] is string ___TimeSinceLastReading ? ___TimeSinceLastReading : default,
                DpoeHourlyEvents = row["DPOE_hourly_events_hot_cold"] is string ___DpoeHourlyEvents ? ___DpoeHourlyEvents : default,
                DpoeHourlyGallons = row["DPOE_hourly_gallons_hot_cold"] is string ___DpoeHourlyGallons ? ___DpoeHourlyGallons : default,
                DpoeHourlyFlowTime = row["DPOE_hourly_flowtime_hot_cold"] is string ___DpoeHourlyFlowTime ? ___DpoeHourlyFlowTime : default,
            };
        }
    }
}