using System.Collections.Immutable;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BigQueryMapping.Generators;

[Generator]
public class BigQueryMapperGenerator : IIncrementalGenerator
{
    private static readonly Regex AttributeConstructorRgx = new(@"^Column\(""(\S+)""",RegexOptions.CultureInvariant | RegexOptions.Compiled,
        matchTimeout: TimeSpan.FromMilliseconds(10));

    private const string AttributeName = "BigQueryMapping.BigQueryMappedAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Any(),
            static (ctx, _) => (ClassDeclarationSyntax)ctx.TargetNode);

        IncrementalValueProvider<(Compilation Compilation, ImmutableArray<ClassDeclarationSyntax>Syntaxes)>
            compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Compilation, source.Syntaxes, spc));

        static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes,
            SourceProductionContext context)
        {
            try
            {
                if (classes.IsDefaultOrEmpty)
                    return;

                var distinctClasses = classes.Distinct();

                var classesToGenerate =
                    GetTypesToGenerate(compilation, distinctClasses, context);

                foreach (var classToGenerate in classesToGenerate)
                {
                    var result = GeneratePartialClass(classToGenerate);
                    context.AddSource($"{classToGenerate.RowClass.Name}.g.cs", SourceText.From(result, Encoding.UTF8));
                }
            }
            catch (Exception e)
            {
                var descriptor = new DiagnosticDescriptor(id: "BQD001",
                    title: "Error creating bigquery mapper",
                    messageFormat: "{0} {1}",
                    category: "BigQueryMapperGenerator",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true);

                context.ReportDiagnostic(Diagnostic.Create(descriptor, null, e.Message, e.StackTrace));
            }
        }
    }

    static IEnumerable<ClassToGenerate> GetTypesToGenerate(Compilation compilation,
        IEnumerable<ClassDeclarationSyntax> classes,
        SourceProductionContext ctx)
    {
        foreach (var @class in classes)
        {
            Debug.WriteLine($"Checking class {@class}");
            ctx.CancellationToken.ThrowIfCancellationRequested();

            var semanticModel = compilation.GetSemanticModel(@class.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(@class) is not INamedTypeSymbol classSymbol)
                continue;

            var info = new ClassToGenerate(classSymbol, new());
            foreach (var member in classSymbol.GetMembers())
            {
                if (member is IPropertySymbol { SetMethod: { } } propertySymbol)
                {
                    var columnName = propertySymbol.Name;
                    var attributes = propertySymbol.GetAttributes();
                    var columnAttribute = attributes.FirstOrDefault(ad =>
                        ad.AttributeClass?.ToDisplayString() == typeof(ColumnAttribute).FullName);

                    if (columnAttribute is not null)
                    {
                        var attributeSyntax = columnAttribute.ApplicationSyntaxReference?.GetSyntax().GetText();
                        if (attributeSyntax is not null)
                        {
                            var match = AttributeConstructorRgx.Match(attributeSyntax.ToString());
                            if (match.Success && match.Groups[1].Success)
                            {
                                columnName = match.Groups[1].Value;
                            }
                        }
                    }

                    info.Properties.Add((columnName, propertySymbol));
                }
            }

            yield return info;
        }
    }


    static string GeneratePartialClass(ClassToGenerate c)
    {
        var sb = new StringBuilder();
        sb.Append($@"// <auto-generated/>
namespace {c.RowClass.ContainingNamespace.ToDisplayString()}
{{
    public partial class {c.RowClass.Name} : BigQueryMapping.IBigQueryGenerated<{c.RowClass.Name}>
    {{
        public static {c.RowClass.Name} FromBigQueryRow(Google.Cloud.BigQuery.V2.BigQueryRow row)
        {{
            return new {c.RowClass.Name}
            {{");

        foreach (var (columnName, property) in c.Properties)
        {
            // would like to check if key exists but don't see any sort of ContainsKey implemented on BigQueryRow
            var tempName = $"___{property.Name}";
            var basePropertyType = property.Type.WithNullableAnnotation(NullableAnnotation.None).ToDisplayString();
            if (basePropertyType.EndsWith("?"))
            {
                basePropertyType = basePropertyType.Substring(default, basePropertyType.Length - 1);
            }

            sb.Append($@"
                {property.Name} = row[""{columnName}""] is {basePropertyType} {tempName} ? {tempName} : default,");
        }

        sb.Append($@"
            }};
        }}
    }}
}}");
        return sb.ToString();
    }

    private record struct ClassToGenerate(INamedTypeSymbol RowClass,
        List<(string ColumnName, IPropertySymbol Property)> Properties);
}